// Generated by https://quicktype.io

export default interface TodoAPI {
  id: number;
  title: string;
  completed: boolean;
  deleted: boolean;
}

export interface TodoState {
  loading: boolean;
  data: TodoAPI[] | [];
  error: string | '';
  alert: string | '';
}
